# Generated by Django 2.2 on 2021-03-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default='ecray', max_length=45),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Emily', max_length=255),
        ),
    ]
